version: '3'
services:
  app:
    build: .
    restart: on-failure
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
  postgres:
    image: postgres:9-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./data/pgsql/data:/var/lib/postgresql/data
      - ./data/pgsql/config:/etc/postgresql
      - ./data/pgsql/logs:/var/log/postgresql/
  admin:
    image: sosedoff/pgweb
    restart: always
    ports:
      - 10000:8081
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    restart: always
    env_file:
      - ./.env
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/elastic:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    env_file:
      - ./.env
    ports:
      - 10001:5601
    links:
      - elasticsearch
